### ISSUE TITLE
Problema para acceder al directorio donde monte sac-cli

### ISSUE THREAD

**Issue by fedebanca** [sisoputnfrba/foro#1549]
Buenas.

Me surgió un problema en el cual las consultas o intentos de acceso al directorio donde monte sac-cli no pueden realizarse.
Inicialmente lo que hice fue crear un proceso de prueba, que ejecutara varias de las funciones que implementamos en sac-server, pero no aparecía nada, ni en el debug de sac-cli, ni en al consola de sac-server.
Luego intente realizar las consultas directamente por consola, pero la respuesta que recibía era esta:

`mkdir: cannot create directory ‘/home/utnso/directorioDePrueba/unDirectorio’: Input/output error`

/home/utnso/directorioDePrueba es donde esta montado sac-cli. Este es el error que me tira, y solo lo hace si esta montado sac-cli. una vez desmonto el directorio con "umount", puedo hacer consultas al directorio de forma normal

Lo raro es que apenas inicio el filesystem, algún proceso ya le hace consultas al sac-cli, que si llegan al servidor y son atendidas.

Esto es lo que imprime el debug de sac-cli:
```
FUSE library version: 2.9.4
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003fffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 2659
   unique: 2, error: -38 (Function not implemented), outsize: 16
unique: 3, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 2558
   unique: 3, success, outsize: 32
unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 3531
LOOKUP /.xdg-volume-info
getattr /.xdg-volume-info
statRetorno: 
ino: 751257 
mode: 0 
size: 511 
blksize: 29 
blocks: 0 
mtim: 4096 
   NODEID: 2
   unique: 4, success, outsize: 144
unique: 5, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2558
getattr /
statRetorno: 
ino: 751257 
mode: 0 
size: 511 
blksize: 0 
blocks: 0 
mtim: 4096 
   unique: 5, success, outsize: 120
unique: 7, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 7, success, outsize: 16
unique: 6, opcode: LOOKUP (1), nodeid: 1, insize: 52, pid: 3530
LOOKUP /autorun.inf
getattr /autorun.inf
statRetorno: 
ino: 751257 
mode: 0 
size: 511 
blksize: 21 
blocks: 0 
mtim: 4096 
   NODEID: 3
   unique: 6, success, outsize: 144
```

Y esto lo que imprime la consola del sac-server (cada vez que le llega un getattr, imprime el path que recibió):

```
El path mandado es: /.xdg-volume-info 
El path mandado es: / 
El path mandado es: /autorun.inf 
```

Desde ya, muchas gracias.
