### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by tomasanchez** [sisoputnfrba/foro#2552]
Como andan?

Hay alguna chance de poder usar GitHub Actions workflows para CI?

### 📝 Pasos para reproducir el error

Crear un workflow con un step que corra un make.

Lo que quiero correr es:

```yml
name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo make install

    - name: Build application
      run: make all
```

### 💻 Logs

Obtengo:

```
GitHub Actions workflows can't be executed on this repository.
The billing plan for sisoputnfrba does not include access to GitHub Actions. 
Please contact the organization owner or billing manager for questions about the current billing plan
```
